### ISSUE TITLE
kadm5_init_with_password() -  KDC has no support for encryption type

### ISSUE THREAD

**Issue by plrunner** [opinsys/smbkrb5pwd#10]
I got this when trying to change a password:
Mar 15 03:00:47 ldap3 slapd[5844]: smbkrb5pwd conn=1013 op=1 : kadm5_init_with_password() failed for user test (smbkrb5pwd/my.host@MY.REALM): KDC has no support for encryption type

So I run ktadd again omitting the -e option so that the keytab was exported for every supported enctype-salttype pair. Now I get the following when running slappasswd:
smbkrb5pwd conn=1001 op=1 : forked password change process did not complete in 15s

Am on Centos6 and openldap 2.4.40.
PL

**Comment by plrunner** [comment]
Ok, I found the solution in the MIT documentation (http://web.mit.edu/Kerberos/krb5-1.13/doc/admin/troubleshoot.html#init-creds-etype-nosupp).
Briefly, I had to  add `allow_weak_crypto = true` under `[libdefaults]` in /etc/krb5.conf.

Now I get another error, but that's another story :-).

**Comment by Fraterius** [comment]
The below statement in [libdefaults] should be in the README as without it latest Kerberos won't work.

allow_weak_crypto = true

besides that maybe it's a good idea to use latest encryption as it's not good practice to use Kerberos with such settings.
