### ISSUE TITLE
kadm5_init_with_password()  - permission denied

### ISSUE THREAD

**Issue by plrunner** [opinsys/smbkrb5pwd#11]
I followed the setup instructions but I get the following in the log file when using ldappasswd:

AS_REQ (7 etypes {18 17 16 23 1 3 2}) 192.168.2.217: ISSUE: authtime 1426412497, etypes {rep=1 tkt=16 ses=16}, smbkrb5pwd/host.fqdn@FQDN for kadmin/admin@FQDN
smbkrb5pwd conn=1006 op=1 : kadm5_init_with_password() failed for user test (smbkrb5pwd/host.fqdn@FQDN): Permission denied

I tried putting  `smbkrb5pwd/host.fqdn@FQDN` into the kadm5.acl file giving it all permissions, but get the same error.

PL

**Comment by vmlintu** [comment]
Are you using smbkrb5pwd or smbkrb5pwd_srv module? If smbkrb5pwd_srv, does slapd process have read access to the stash file? If you are using the smbkrb5pwd module, does slapd process have read access to the keytab file?

**Comment by plrunner** [comment]
Am using smbkrb5pwd. Yes, that was the problem. I had set the correct group and permission the first time I exported the keytab. Then I removed and re-exported it when troublshooting a different problem and forgot to adjust it agian.

Thanks for the time.
